@api_HostAddress = http://localhost:5053

###
//Gets all the "Enrolled" users of an event
GET http://localhost:5053/events/7/check-list


###
//Check the user {id} as "hasAssisted" and add him to the Attendance table 
POST http://localhost:5053/events/7/check-list/7


###
//Delete a user from the Attendance table and change his status to "hasAssisted: false"
DELETE  http://localhost:5053/events/7/check-list/9
