services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong1Pass

    volumes:
      - ./initdb.sql:/usr/src/app/initdb.sql:ro
      - ./seed_events.sql:/usr/src/app/seed_events.sql:ro
      - ./seed_users_inscriptions_attendance.sql:/usr/src/app/seed_users_inscriptions_attendance.sql:ro
      - ./seed_massive_participation.sql:/usr/src/app/seed_massive_participation.sql:ro
      - ./setup.sh:/usr/src/app/setup.sh

    entrypoint: ["/bin/bash", "/usr/src/app/setup.sh"]
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "127.0.0.1",
          "-U",
          "sa",
          "-P",
          "YourStrong1Pass",
          "-C",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
