services:
  postgres:
    image: postgres:17-alpine
    container_name: eventorganizer-postgres
    ports:
      - "127.0.0.1:5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=EventOrganizer

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/01_initdb.sql:ro
      - ./seed_events.sql:/docker-entrypoint-initdb.d/02_seed_events.sql:ro
      - ./seed_users_inscriptions_attendance.sql:/docker-entrypoint-initdb.d/03_seed_users_inscriptions_attendance.sql:ro
      - ./seed_massive_participation.sql:/docker-entrypoint-initdb.d/04_seed_massive_participation.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d EventOrganizer"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

volumes:
  postgres_data:
