CREATE TABLE IF NOT EXISTS "Role" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RolName" VARCHAR(50) NOT NULL,
    CONSTRAINT "UQ_Role_RolName" UNIQUE ("RolName"),
    CONSTRAINT "CK_Role_RolName_NotBlank" CHECK (LENGTH(BTRIM("RolName")) > 0)
);

CREATE TABLE IF NOT EXISTS "User" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserPass" VARCHAR(50) NOT NULL,
    "UserName" VARCHAR(100) NOT NULL,
    "Email" VARCHAR(100) NOT NULL,
    "Biography" VARCHAR(2000) NULL,
    "UrlImageProfile" TEXT NULL,
    "PreferredLanguage" VARCHAR(50) NULL DEFAULT 'Español',
    "Active" BOOLEAN NOT NULL DEFAULT TRUE,
    "RoleId" INTEGER NOT NULL,
    "IdCard" INTEGER NULL,
    "ImageFileUser" TEXT NULL,
    CONSTRAINT "UQ_User_Email" UNIQUE ("Email"),
    CONSTRAINT "FK_User_Role" FOREIGN KEY ("RoleId") REFERENCES "Role"("Id"),
    CONSTRAINT "CK_User_UserPass_NotBlank" CHECK (LENGTH(BTRIM("UserPass")) > 0),
    CONSTRAINT "CK_User_UserName_NotBlank" CHECK (LENGTH(BTRIM("UserName")) > 0),
    CONSTRAINT "CK_User_Email_NotBlank" CHECK (LENGTH(BTRIM("Email")) > 0),
    CONSTRAINT "CK_User_IdCard_Positive" CHECK ("IdCard" IS NULL OR "IdCard" > 0)
);

CREATE TABLE IF NOT EXISTS "Category" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NameCategory" VARCHAR(50) NOT NULL,
    CONSTRAINT "UQ_Category_NameCategory" UNIQUE ("NameCategory"),
    CONSTRAINT "CK_Category_NameCategory_NotBlank" CHECK (LENGTH(BTRIM("NameCategory")) > 0)
);

CREATE TABLE IF NOT EXISTS "OrganizerEntity" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityName" VARCHAR(200) NOT NULL,
    CONSTRAINT "UQ_OrganizerEntity_EntityName" UNIQUE ("EntityName"),
    CONSTRAINT "CK_OrganizerEntity_EntityName_NotBlank" CHECK (LENGTH(BTRIM("EntityName")) > 0)
);

CREATE TABLE IF NOT EXISTS "Event" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "Place" VARCHAR(100) NOT NULL,
    "Title" VARCHAR(100) NOT NULL,
    "EventDescription" VARCHAR(300) NOT NULL,
    "CategoryId" INTEGER NOT NULL,
    "OrganizerId" INTEGER NOT NULL,
    "OrganizerEntityId" INTEGER NOT NULL,
    "AvalaibleEntries" INTEGER NOT NULL,
    "ApprovedState" BOOLEAN NOT NULL DEFAULT FALSE,
    "ImageFileEvent" TEXT,
    "IsVirtual" BOOLEAN NOT NULL,
    "ReminderSent" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_Event_Category" FOREIGN KEY ("CategoryId") REFERENCES "Category"("Id"),
    CONSTRAINT "FK_Event_Organizer" FOREIGN KEY ("OrganizerId") REFERENCES "User"("Id"),
    CONSTRAINT "FK_Event_OrganizerEntity" FOREIGN KEY ("OrganizerEntityId") REFERENCES "OrganizerEntity"("Id"),
    CONSTRAINT "CK_Event_Place_NotBlank" CHECK (LENGTH(BTRIM("Place")) > 0),
    CONSTRAINT "CK_Event_Title_NotBlank" CHECK (LENGTH(BTRIM("Title")) > 0),
    CONSTRAINT "CK_Event_Description_NotBlank" CHECK (LENGTH(BTRIM("EventDescription")) > 0),
    CONSTRAINT "CK_Event_AvailableEntries_Positive" CHECK ("AvalaibleEntries" > 0)
);

CREATE TABLE IF NOT EXISTS "CanceledEvent" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" INTEGER NOT NULL,
    "Reason" VARCHAR(500) NOT NULL,
    CONSTRAINT "UQ_CanceledEvent_EventId" UNIQUE ("EventId"),
    CONSTRAINT "FK_CanceledEvent_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "CK_CanceledEvent_Reason_NotBlank" CHECK (LENGTH(BTRIM("Reason")) > 0)
);

CREATE TABLE IF NOT EXISTS "Inscriptions" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "InscriptionDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_Inscriptions_Event_User" UNIQUE ("EventId", "UserId"),
    CONSTRAINT "FK_Inscriptions_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "FK_Inscriptions_User" FOREIGN KEY ("UserId") REFERENCES "User"("Id")
);

CREATE TABLE IF NOT EXISTS "Attendance" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    CONSTRAINT "UQ_Attendance_Event_User" UNIQUE ("EventId", "UserId"),
    CONSTRAINT "FK_Attendance_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "FK_Attendance_User" FOREIGN KEY ("UserId") REFERENCES "User"("Id")
);

CREATE TABLE IF NOT EXISTS "Announcement" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WriterId" INTEGER NOT NULL,
    "EventId" INTEGER,
    "PublicationDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Title" VARCHAR(100) NOT NULL,
    "About" VARCHAR(100) NOT NULL,
    "Body" VARCHAR(1000) NOT NULL,
    
    CONSTRAINT "FK_Announcement_User" FOREIGN KEY ("WriterId") REFERENCES "User"("Id"),
    CONSTRAINT "FK_Announcement_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "CK_Announcement_Title_NotBlank" CHECK (LENGTH(BTRIM("Title")) > 0),
    CONSTRAINT "CK_Announcement_About_NotBlank" CHECK (LENGTH(BTRIM("About")) > 0),
    CONSTRAINT "CK_Announcement_Body_NotBlank" CHECK (LENGTH(BTRIM("Body")) > 0)
);

CREATE TABLE IF NOT EXISTS "Mail" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WriterId" INTEGER NOT NULL,
    "EventId" INTEGER NOT NULL,
    "Title" VARCHAR(100) NOT NULL,
    "About" VARCHAR(100) NOT NULL,
    "Body" VARCHAR(1000) NOT NULL,
    CONSTRAINT "FK_Mail_User" FOREIGN KEY ("WriterId") REFERENCES "User"("Id"),
    CONSTRAINT "FK_Mail_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "CK_Mail_Title_NotBlank" CHECK (LENGTH(BTRIM("Title")) > 0),
    CONSTRAINT "CK_Mail_About_NotBlank" CHECK (LENGTH(BTRIM("About")) > 0),
    CONSTRAINT "CK_Mail_Body_NotBlank" CHECK (LENGTH(BTRIM("Body")) > 0)
);
