CREATE TABLE IF NOT EXISTS "EventReminderLog" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "ReminderType" VARCHAR(50) NOT NULL,
    "SentAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_EventReminderLog_Event_User_Type" UNIQUE ("EventId", "UserId", "ReminderType"),
    CONSTRAINT "FK_EventReminderLog_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "FK_EventReminderLog_User" FOREIGN KEY ("UserId") REFERENCES "User"("Id"),
    CONSTRAINT "CK_EventReminderLog_Type_NotBlank" CHECK (LENGTH(BTRIM("ReminderType")) > 0)
);
