ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "Biography" VARCHAR(2000) NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "UrlImageProfile" TEXT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "PreferredLanguage" VARCHAR(50) NULL DEFAULT 'English';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ImageFileUser" TEXT NULL;
