CREATE TABLE IF NOT EXISTS "ModerationActionLog" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" INTEGER NOT NULL,
    "ModeratorUserId" INTEGER NULL,
    "Action" VARCHAR(30) NOT NULL,
    "Reason" VARCHAR(500) NULL,
    "ActionDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_ModerationActionLog_Event" FOREIGN KEY ("EventId") REFERENCES "Event"("Id"),
    CONSTRAINT "FK_ModerationActionLog_User" FOREIGN KEY ("ModeratorUserId") REFERENCES "User"("Id") ON DELETE SET NULL,
    CONSTRAINT "CK_ModerationActionLog_Action_NotBlank" CHECK (LENGTH(BTRIM("Action")) > 0)
);
